### ISSUE TITLE
Clicking on any post opens the newest

### ISSUE THREAD

**Issue by webtheo** [Vobe-io/vobe#19]
**Describe the bug**
Clicking on any (older) post opens every time the site for the newest.

**To Reproduce**
1. Go to the homepage
2. Click on any older post
3. You will be redirected to the newest post

**Expected behavior**
It should show the site containing the clicked post

**Screenshots**
![42DIHmIW0C](https://user-images.githubusercontent.com/43825134/74104440-df112400-4b54-11ea-8c51-e4b685ac9c0c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version: Version 1.5.13 Canary

**Comment by TimoA200** [comment]
Blame yourself if you use the Canery version. lol

**Comment by Comeza** [comment]
please provide some information about the system you use.
