### ISSUE TITLE
If logged in no other user profiles can be viewed

### ISSUE THREAD

**Issue by webtheo** [Vobe-io/vobe#20]
**Describe the bug**
If you are logged in you can not view any other user profile as it always redirects to your own profile.

**To Reproduce**
1. Log-in
2. Click on any other profile
3. Your own profile will show up

**Expected behavior**
You should be able to see the clicked profile

**Screenshots**
![4AMoohGk6g](https://user-images.githubusercontent.com/43825134/74104603-7d51b980-4b56-11ea-83c3-9de3306d4dd6.png)

**Comment by Comeza** [comment]
related to #24
