### ISSUE TITLE
Connect Vobe to brave rewards

### ISSUE THREAD

**Issue by webtheo** [Vobe-io/vobe#22]
**Is your feature request related to a problem? Please describe.**
If Brave users are using Vobe regularly they may give some BAT automatically to Vobe with activated "Auto-Contribute".

**Describe the solution you'd like**
Vobe should be BAT verified on Brave Publishers so you could accept and cash-out BAT.

**Comment by TimoA200** [comment]
Currently we aren't planning to connect vobe with brave rewards.

**Comment by webtheo** [comment]
sad to hear that.
