### ISSUE TITLE
Not able to click on post after sending without reload

### ISSUE THREAD

**Issue by TimoA200** [Vobe-io/vobe#26]
**Describe the bug**
If your are clicking on a post immediately after sending it and without reloading the page, nothing happens.
You have to reload the page to click on the post.

**To Reproduce**
1. Send a post
2. Click on post
3. Nothing happens
4. Reload the page
5. Click on post
6. Works

**Expected behavior**
You can click on the post immediately after sending it.

**Comment by Comeza** [comment]
fixed
