### ISSUE TITLE
Converting to Angular

### ISSUE THREAD

**Issue by Comeza** [Vobe-io/vobe#46]
**Is your improvement request related to a problem? Please describe.**
The code is a fucking mess.
I mean what in the name of god is [this](https://github.com/Vobe-io/vobe/blob/master/routes/api/post/create.js)
You can't properly read what the code does without asking.
(((Maybe add comments)))

**Describe what could be improved in your opinion**
Convert to Angular

**Comment by TimoA200** [comment]
Done😀
