### ISSUE TITLE
Invalid Hex-Id on post route

### ISSUE THREAD

**Issue by Comeza** [Vobe-io/vobe#47]
**Describe the bug**
The bug occours if you enter a valid bson-id on /v/BSON-ID but it doesn't refer to a post id.

**To Reproduce**
1. Click on any post
2. Chnage a letter in the url bar
![image](https://user-images.githubusercontent.com/37485277/74257556-4bc32480-4cf5-11ea-840d-18c1b714cf86.png)
For example here the 5 to a 6

3. Enjoy infinite loading

**Expected behavior**
Getting an error message

**Comment by TimoA200** [comment]
The problem was solved as a part of this issue but was destroyed because of a merge
https://github.com/Vobe-io/vobe/issues/30
