### ISSUE TITLE
New lines restricted

### ISSUE THREAD

**Issue by webtheo** [Vobe-io/vobe#7]
After someone makes 2 new lines to his post the other new lines will not be displayed.

**Comment by TimoA200** [comment]
We already noticed this issue and we are just about to fix it

**Comment by Comeza** [comment]
This is related to [this](https://github.com/Vobe-io/vobe/commit/8bc978bb7787e8f2f2b139683dee6c62a0ddf6a7)

**Comment by TimoA200** [comment]
That could be true
